{{- if .Values.mailrelay.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-app
  labels:
    {{- include "mailrelay.labels" . | nindent 4 }}
  {{- with .Values.mailrelay.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.mailrelay.ingress.className }}
  {{- if .Values.mailrelay.ingress.tls }}
  tls:
    {{- range .Values.mailrelay.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.mailrelay.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Release.Name }}-app
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }} 