apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "mailrelay.labels" . | nindent 4 }}
type: Opaque
data:
  NEXTAUTH_SECRET: {{ .Values.mailrelay.secrets.nextauthSecret | b64enc }}
  OIDC_ISSUER_URL: {{ .Values.mailrelay.secrets.oidcIssuerUrl | b64enc }}
  OIDC_CLIENT_ID: {{ .Values.mailrelay.secrets.oidcClientId | b64enc }}
  OIDC_CLIENT_SECRET: {{ .Values.mailrelay.secrets.oidcClientSecret | b64enc }}
  POSTGRES_URL: {{ .Values.mailrelay.secrets.postgresUrl | b64enc }} 