# Default values for mailrelay.
# This is a YAML-formatted file.

global:
  environment: production

# SMTP Client UI configuration
smtpClientUi:
  enabled: true
  replicaCount: 1
  image:
    repository: mailrelay-smtp-client
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
    smtpPort: 2525
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    NODE_ENV: production
    APP_MODE: smtp-client-ui
    PORT: "3000"
    SMTP_SERVER_PORT: "2525"
    POSTGRES_URL: "postgres://postgres:postgres@mailrelay-postgres:5432/postgres"
    KAFKA_BROKERS: "mailrelay-kafka:9092"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: mailrelay.example.com
        paths:
          - path: /
            pathType: Prefix

# SMTP Server configuration
smtpServer:
  enabled: true
  replicaCount: 1
  image:
    repository: mailrelay-smtp-client
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    smtpPort: 2526
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    NODE_ENV: production
    APP_MODE: smtp
    SMTP_SERVER_PORT: "2526"
    POSTGRES_URL: "postgres://postgres:postgres@mailrelay-postgres:5432/postgres"
    KAFKA_BROKERS: "mailrelay-kafka:9092"

# PostgreSQL configuration
postgres:
  enabled: true
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard

# Kafka configuration
kafka:
  enabled: true
  image:
    repository: bitnami/kafka
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9092
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    KAFKA_CFG_NODE_ID: "1"
    KAFKA_CFG_PROCESS_ROLES: "controller,broker"
    KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@mailrelay-kafka:9093"
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    ALLOW_PLAINTEXT_LISTENER: "yes"
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard

# Kafka UI configuration
kafkaUi:
  enabled: true
  image:
    repository: provectuslabs/kafka-ui
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    KAFKA_CLUSTERS_0_NAME: mailrelay
    KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: mailrelay-kafka:9092
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: kafka-ui.example.com
        paths:
          - path: /
            pathType: Prefix

# MailHog configuration
mailhog:
  enabled: true
  image:
    repository: mailhog/mailhog
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    smtpPort: 1025
    uiPort: 8025
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: mailhog.example.com
        paths:
          - path: /
            pathType: Prefix

# MockServer configuration
mockserver:
  enabled: true
  image:
    repository: mockserver/mockserver
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 1080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  env:
    MOCKSERVER_SERVER_PORT: "1080"
    MOCKSERVER_LOG_LEVEL: "INFO"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: mockserver.example.com
        paths:
          - path: /
            pathType: Prefix 